front-to-back/ViewModels/Contact/ContactIndexViewModel.cs
using front_to_back.Models;

namespace front_to_back.ViewModels
{
    public class ContactIndexViewModel
    {
        public ContractIntroComponent ContractIntroComponent { get; set; }

        public CreateWithUs CreateWithUs { get; set; }
        public List<ContactFormComponent> ContactFormComponent { get; set; }
    }
}

front-to-back/Areas/Admin/Controllers/ContactController.cs
using front_to_back.DAL;
using front_to_back.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using front_to_back.Models;
using front_to_back.Migrations;
using System.IO;
using front_to_back.Areas.Admin.ViewModels;
using front_to_back.Helpers;

namespace front_to_back.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ContactController : Controller
    {
        private readonly AppDbContext _appDbContext;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IFileService _fileService;

        public ContactController(AppDbContext appDbContext, IWebHostEnvironment webHostEnvironment, IFileService fileService)
        {
            _appDbContext = appDbContext;
            _webHostEnvironment = webHostEnvironment;
            _fileService = fileService;
        }
        public async Task<IActionResult> Index()

        {
            var contractIntroComponent = await _appDbContext.ContractIntroComponent.FirstOrDefaultAsync();

            if (contractIntroComponent == null)
            {
                return RedirectToAction("create");
            }

            var model = new ContactIntroViewModel
            {
                contractIntroComponents = await _appDbContext.ContractIntroComponent.ToListAsync()
            };
            return View(model);
        }

        #region Create
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ContractIntroComponent contractIntro)
        {

            if (!_fileService.CheckFile(contractIntro.Photo))
            {
                ModelState.AddModelError("Photo", "Incorrect type");
                return View(contractIntro);
            }

            int maxSize = 1000;
            if (!_fileService.MaxSize(contractIntro.Photo,maxSize))
            {
                ModelState.AddModelError("Photo", $"Photo size must be {maxSize}kb");
                return View(contractIntro);
            }


            contractIntro.FilePath = await _fileService.UploadAsync(contractIntro.Photo, _webHostEnvironment.WebRootPath);

            if (!ModelState.IsValid) return View(contractIntro);

            await _appDbContext.AddAsync(contractIntro);
            await _appDbContext.SaveChangesAsync();

            return RedirectToAction("index");
        }

        #endregion

        #region Update
        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var contactintrocomponent = await _appDbContext.ContractIntroComponent.FindAsync(id);
            if (contactintrocomponent == null) return NotFound();

            var model = new ContactIntroUpdateViewModel
            {
                Id = contactintrocomponent.Id,
                Title = contactintrocomponent.Title,
                Description = contactintrocomponent.Description,
                FilePath = contactintrocomponent.FilePath
             
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, ContactIntroUpdateViewModel model)
        {
            var dbcontractIntroComponent = await _appDbContext.ContractIntroComponent.FindAsync(id);

            if (id != model.Id) return BadRequest();
            if (dbcontractIntroComponent == null) return NotFound();

            if (model.Photo != null)
            {
    
                if (!_fileService.CheckFile(model.Photo))
                {
                    ModelState.AddModelError("Photo","File format was incorrect ");
                    return View(model);
                }
   
                var maxSize = 1000;

                if (!_fileService.MaxSize(model.Photo,maxSize))
                {
                    ModelState.AddModelError("Photo",$"Photo size must be less {maxSize}kb");
                    return View(model);
                }

                _fileService.Delete(_webHostEnvironment.WebRootPath, dbcontractIntroComponent.FilePath);
                dbcontractIntroComponent.FilePath = await
                _fileService.UploadAsync(model.Photo, _webHostEnvironment.WebRootPath);
            }

            if (!ModelState.IsValid) return View(model);

            dbcontractIntroComponent.Title = model.Title;
            dbcontractIntroComponent.Description = model.Description;

            await _appDbContext.SaveChangesAsync();

            return RedirectToAction("index");
        }

        #endregion

        #region Details
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var dbcontactIntroComponent = await _appDbContext.ContractIntroComponent.FindAsync(id);
            if (dbcontactIntroComponent == null) return NotFound();

            return View(dbcontactIntroComponent);

        }

        #endregion

        #region Delete
        [HttpGet]

        public async Task<IActionResult> Delete(int id)
        {
            var dbContactIntroComponent = await _appDbContext.ContractIntroComponent.FindAsync(id);
            if (dbContactIntroComponent == null) return NotFound();
            return View(dbContactIntroComponent);
        }

        [HttpPost]

        public async Task<IActionResult> DeleteComponent(int id)
        {
            var dbContactIntroComponent = await _appDbContext.ContractIntroComponent.FindAsync(id);
            if (dbContactIntroComponent == null) return NotFound();

            _fileService.Delete(_webHostEnvironment.WebRootPath, dbContactIntroComponent.FilePath);
            _appDbContext.ContractIntroComponent.Remove(dbContactIntroComponent);

            await _appDbContext.SaveChangesAsync();
            return RedirectToAction("index");
        }

        #endregion
    }

}

front-to-back/Controllers/ContactController.cs
using front_to_back.DAL;
using front_to_back.Models;
using front_to_back.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace front_to_back.Controllers
{
    public class ContactController : Controller
    {
        private readonly AppDbContext _appDbContext;

        public ContactController(AppDbContext appDbContext)
        {
            _appDbContext = appDbContext;
        }
        public async Task<IActionResult> Index()
        {
            var model = new ContactIndexViewModel
            {
                ContractIntroComponent = await _appDbContext.ContractIntroComponent.FirstOrDefaultAsync(),
                CreateWithUs = await _appDbContext.CreateWithUs.FirstOrDefaultAsync(),
                ContactFormComponent = await _appDbContext.ContactFormComponents.ToListAsync()
            };
            return View(model);
        }
    }
}

front-to-back/ViewComponents/ObjectiveComponentViewComponent.cs
using front_to_back.DAL;
using front_to_back.ViewModels.About;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace front_to_back.ViewComponents
{
    public class ObjectiveComponentViewComponent : ViewComponent
    {
        private readonly AppDbContext _appDbContext;

        public ObjectiveComponentViewComponent(AppDbContext appDbContext)
        {
            _appDbContext = appDbContext;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = new AboutIndexViewModel
            {
                ourWorks = await _appDbContext.OurWorks.ToListAsync()

            };
            return View(model);
        }
    }
}

front-to-back/Views/Contact/Index.cshtml
@using front_to_back.ViewModels;
@model ContactIndexViewModel;
<section class="bg-light">
    <div class="container py-4">
        <div class="row align-items-center justify-content-between">
            <div class="contact-header col-lg-4">

                @{
                    if (Model.ContractIntroComponent != null)
                    {
                        <h2> @Model.ContractIntroComponent.Title</h2>
                       
                        @Html.Raw(Model.ContractIntroComponent.Description)
                    }
                }
            </div>
            <div class="contact-img col-lg-5 align-items-end col-md-4">
                <img  src="~/assets/img/@{
                    if(Model.ContractIntroComponent!=null)
{
            @Model.ContractIntroComponent.FilePath
}
}">
            </div>
        </div>
    </div>
</section>
<!-- End Banner Hero -->
@await Component.InvokeAsync("ObjectiveComponent")
<!-- Start Contact -->
<section class="container py-5">

    <h1 class="col-12 col-xl-8 h2 text-left text-primary pt-3">
        @Html.Raw(Model.CreateWithUs.Title)
    </h1>
    @Html.Raw(Model.CreateWithUs.Description)
    <div class="row pb-4">
        <div class="col-lg-4">
            @foreach (var component in Model.ContactFormComponent)
            {
                <div class="contact row mb-4">
                    <div class="contact-icon col-lg-3 col-3">
                        <div class="py-3 mb-2 text-center border rounded text-secondary">
                            <i class='display-6 bx @component.FilePath'></i>
                        </div>
                    </div>
                    <ul class="contact-info list-unstyled col-lg-9 col-9  light-300">
                        @Html.Raw(component.İnfo)
                    </ul>
                </div>

            }
        </div>


        <!-- Start Contact Form -->
        <div class="col-lg-8 ">
            <form class="contact-form row" method="post" action="#" role="form">

                <div class="col-lg-6 mb-4">
                    <div class="form-floating">
                        <input type="text" class="form-control form-control-lg light-300" id="floatingname" name="inputname" placeholder="Name">
                        <label for="floatingname light-300">Name</label>
                    </div>
                </div><!-- End Input Name -->

                <div class="col-lg-6 mb-4">
                    <div class="form-floating">
                        <input type="text" class="form-control form-control-lg light-300" id="floatingemail" name="inputemail" placeholder="Email">
                        <label for="floatingemail light-300">Email</label>
                    </div>
                </div><!-- End Input Email -->

                <div class="col-lg-6 mb-4">
                    <div class="form-floating">
                        <input type="text" class="form-control form-control-lg light-300" id="floatingphone" name="inputphone" placeholder="Phone">
                        <label for="floatingphone light-300">Phone</label>
                    </div>
                </div><!-- End Input Phone -->

                <div class="col-lg-6 mb-4">
                    <div class="form-floating">
                        <input type="text" class="form-control form-control-lg light-300" id="floatingcompany" name="inputcompany" placeholder="Company Name">
                        <label for="floatingcompany light-300">Company Name</label>
                    </div>
                </div><!-- End Input Company Name -->

                <div class="col-12">
                    <div class="form-floating mb-4">
                        <input type="text" class="form-control form-control-lg light-300" id="floatingsubject" name="inputsubject" placeholder="Subject">
                        <label for="floatingsubject light-300">Subject</label>
                    </div>
                </div><!-- End Input Subject -->

                <div class="col-12">
                    <div class="form-floating mb-3">
                        <textarea class="form-control light-300" rows="8" placeholder="Message" id="floatingtextarea"></textarea>
                        <label for="floatingtextarea light-300">Message</label>
                    </div>
                </div><!-- End Textarea Message -->

                <div class="col-md-12 col-12 m-auto text-end">
                    <button type="submit" class="btn btn-secondary rounded-pill px-md-5 px-4 py-2 radius-0 text-light light-300">Send Message</button>
                </div>

            </form>
        </div>
        <!-- End Contact Form -->


    </div>
</section>
<!-- End Contact -->